easy_admin:
    site_name: 'Ffouillet.fr Administration'
    entities:
        # BLOG
        Post:
            class: Fx\BlogBundle\Entity\Post
            form : 
                fields: 
                    - 'title'
                    - 'user'
                    - 'postCategory'
                    - 'heading'
                    - 'content'
                    - 'createdAt'
        PostCategory:
            class: Fx\BlogBundle\Entity\PostCategory
        Comment:
            class: Fx\BlogBundle\Entity\Comment
        # PORTFOLIO
        Project:
            class: Fx\PortfolioBundle\Entity\Project
            form:
                fields:
                    - 'name'
                    - 'user'
                    - { property: 'url', type: 'url' }
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'Fx\CoreBundle\Form\ProjectImageType', by_reference: false, allow_delete: true}, label: 'Screenshots du projet', embedded: true }
                    - 'realizedAt'
                    - { property: 'realizedAtDisplayString', type: 'text', label: 'Date réalisation (string) qui sera affichée sur front' }
                    - 'description'
                    - 'tags'
                    - 'frontendSortOrder'
                    
        Skill:
            class: Fx\PortfolioBundle\Entity\Skill
