easy_admin:
    site_name: 'Ffouillet.fr Administration'
    entities:
        # BLOG
        Post:
            class: Fx\BlogBundle\Entity\Post
            form : 
                fields: 
                    - 'title'
                    - 'user'
                    - 'postCategory'
                    - 'heading'
                    - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
                    - 'createdAt'
        PostCategory:
            class: Fx\BlogBundle\Entity\PostCategory
        Comment:
            class: Fx\BlogBundle\Entity\Comment
        # PORTFOLIO
        Project:
            class: Fx\PortfolioBundle\Entity\Project
            form:
                fields:
                    - 'name'
                    - 'user'
                    - { property: 'url', type: 'text' }
                    - 'projectCategories'
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'Fx\CoreBundle\Form\ProjectImageType', by_reference: false, allow_delete: false}, label: 'Screenshots du projet', embedded: true }
                    - 'realizedAt'
                    - { property: 'realizedAtDisplayString', type: 'text', label: 'Date réalisation (string) qui sera affichée sur front' }
                    - 'description'
                    - 'tags'
                    - 'frontendSortOrder'
            list:
                fields:
                    - 'name'
                    - { property: 'projectCategories', type: 'array'}
                    - 'realizedAtDisplayString'
                    - 'url'
        ProjectCategory:
            class: Fx\PortfolioBundle\Entity\ProjectCategory
        Skill:
            class: Fx\PortfolioBundle\Entity\Skill
            form:
                fields:
                    - 'name'
                    - 'user'
                    - 'frontendSortOrder'
                    - { property: 'imageFile', type: 'vich_image', type_options :  { allow_delete: false } }
            list:
                fields:
                    - 'name'
                    - { property: 'image', type: 'image', base_path: '%app.path.skills_images%' }
                    - 'frontendSortOrder'
        Tool:
            class: Fx\PortfolioBundle\Entity\Tool
            form:
                fields:
                - 'name'
                - 'user'
                - 'level'
                - 'frontendSortOrder'
                - { property: 'imageFile', type: 'vich_image', type_options:  { allow_delete: false } }
            list:
                fields:
                - 'name'
                - { property: 'image', type: 'image', base_path: '%app.path.tools_images%' }
                - 'level'
                - 'frontendSortOrder'
