# See documentations of this bundle for details :
# https://packagist.org/packages/expertcoder/swiftmailer-send-grid-bundle#1.1.0

swiftmailer:
  transport: swiftmailer.mailer.transport.expertcoder_swift_mailer.send_grid.transport
  host:      '%mailer_host%'
  username:  '%mailer_user%'
  password:  '%mailer_password%'
  spool: { type: memory }

expert_coder_swiftmailer_send_grid:
    api_key: %sendgrid_api_key%

services:
  swiftmailer.mailer.transport.expertcoder_swift_mailer.send_grid.transport:
    alias: expertcoder_swift_mailer.send_grid.transport