# Images upload
parameters:
    app.path.projects_images: /uploads/images/realisations
    app.path.skills_images: /uploads/images/competences
    app.path.tools_images: /uploads/images/outils

vich_uploader:
    db_driver: orm
    mappings:
        projects_images:
            uri_prefix:         '%app.path.projects_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.projects_images%'
            directory_namer:
                service: fx.project_image_directory_namer

        skills_images:
            uri_prefix:         '%app.path.skills_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.skills_images%'
            namer:
                service: vich_uploader.namer_origname

        tools_images:
            uri_prefix:         '%app.path.tools_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.tools_images%'
            namer:
                service: vich_uploader.namer_origname
