# app/config/config.yml

liip_imagine:

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~

    # your filter sets are defined here
    filter_sets:

        # use the default cache configuration
        cache: ~ 

        project_thumb:
            quality : 90
            filters : 
                thumbnail : { size: [280,158    ], mode: outbound }
