_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

fx_core:
    resource: "@FxCoreBundle/Resources/config/routing.yml"
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fx_portfolio:
    resource: "@FxPortfolioBundle/Resources/config/routing.yml"
    prefix:   /

fx_user:
    resource: "@FxUserBundle/Resources/config/routing.yml"
    prefix:   /

fx_blog:
    resource: "@FxBlogBundle/Resources/config/routing.yml"
    prefix:   /

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
