<?php

namespace Fx\BlogBundle\Repository;

use Fx\BlogBundle\Entity\Post;
/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostCommentsForDisplay(Post $post) {

        $qb = $this->createQueryBuilder('c');

        $qb->where('c.post = :post')
            ->setParameter('post', $post)
            ->andWhere('c.isValid = true')
            ->orderBy('c.createdAt','DESC');

        return $qb->getQuery()->getResult();

    }
}
