fx_homepage:
    path:     /
    defaults: { _controller: FxCoreBundle:Main:index }

fx_ajax_handle_contact_form:
    path:    /ajax/handleContactForm
    defaults: { _controller: FxCoreBundle:Main:handleContactForm}
