services:
#    fx_core.example:
#        class: Fx\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    fx.strings_tools:
        class: Fx\CoreBundle\Service\FxStringsTools
        arguments: ~

    fx.email_sender:
        class: Fx\CoreBundle\Service\FxEmailSender
        arguments:
            $mailer: '@swiftmailer.mailer.default'
            $mail_to: '%mail_to%'
            $twig: '@twig'

    fx.project_image_directory_namer:
        class: Fx\CoreBundle\Service\ProjectImageDirectoryNamer
        arguments: ~

    #fx.encoded_password_generator:
    #    class: Fx\CoreBundle\Service\FxEncodedPasswordGenerator
    #    arguments:
    #        $encoder: '@security.user_password_encoder.generic'
